export const ProjectListing = [
  {
    client: "inQuba",
    title: "Customer journey management software",
    image: "/projects/inquba-journey-management.png",
    description: [
      "Design all UI components from scratch",
      "Build interactive prototypes that emulate the end product in Adobe XD & Figma",
      "UX best practice techniques",
      "HTML & CSS working prototypes",
      "Style guide",
    ],
    href: "projects/inquba",
    category: "UI/UX",
  },

  {
    client: "Go.Compare",
    title: "Design system for all insurance question sets",
    image: "/projects/goco-design-system.png",
    description: [
      "Build a comprehensive design system from scratch",
      "Extend Figma's styles to component patterns with on & off switches",
      "Ensure consistency across desktop, tablet & mobile views",
    ],
    href: "projects/gocompare-design-system",
    category: "UI/UX",
  },
  {
    client: "MultiChoice",
    title: "Self service mobile application",
    image: "/projects/multichoice-self-service-mobile-app.png",
    description: [
      "Wireframing mobile app screens",
      "UI design for user flows",
      "Manage & delegate work among team members",
      "Interactive prototype in UXPin",
    ],
    href: "projects/multichoice-mobile-app",
    category: "UI/UX",
  },
  // {
  //   client: "Agency work",
  //   title: "Find the bunny Easter campaign",
  //   image: "/projects/freelance-emperors-golden-bunny.png",
  //   description: [
  //     "Concept design",
  //     "Photoshop manipulation",
  //     "3D design & animation",
  //     "Motion graphics",
  //   ],
  //   href: "",
  //   category: "Design",
  // },
  {
    client: "Freelance",
    title: "Giftalot Africa. eCommerce WordPress website",
    image: "/projects/giftalot.png",
    description: [
      "Website design and branding",
      "All product shot photography",
      "WordPress development",
      "WooCommerce integration",
      "E-mail marketing (Mailchimp)",
    ],
    href: "projects/giftalot-africa",
    category: "WordPress",
  },
  {
    client: "MultiChoice",
    title: "DStv Self Service website redesign",
    image: "/projects/dstv-redesign.png",
    description: [
      "Information architecture",
      "Wireframes",
      "UI design",
      "Manage tasks among team members",
      "Research gathering",
      "Quantitative insights",
    ],
    href: "projects/multichoice-dstv-website-redesign",
    category: "UI/UX",
  },
  {
    client: "inQuba",
    title: "Dynamic dialogues ideation exercise",
    image: "/projects/inquba-dynamic-dialogues.png",
    description: [
      "Low and high fidelity designs",
      "Many iterations",
      "Validate UI designs with stakeholders and iterate again",
    ],
    href: "projects/inquba-dynamic-dialogues",
    category: "UI/UX",
  },
  {
    client: "Go.Compare",
    title: "Email settings with the 'Preference Centre'",
    image: "/projects/goco-preference-centre.png",
    description: [
      "Low & high fidelity designs",
      "Interactive prototype in Figma",
      "Examine, plot and refine the user journey",
    ],
    href: "projects/gocompare-preference-centre",
    category: "UI/UX",
  },
  {
    client: "Go.Compare",
    title: "Home insurance question set",
    image: "/projects/goco-home-journey.png",
    description: [
      "Competitor research",
      "Update the insurance journey's design style to Go.Compare's latest version",
    ],
    href: "projects/gocompare-home-insurance",
    category: "UI/UX",
  },
  {
    client: "MultiChoice",
    title: "Landing and login pages",
    image: "/projects/multichoice-webportal-tablet.png",
    description: [
      "UI design for landing & login pages",
      "Brand (logo) identity",
      "3D design elements",
      "HTML5, CSS (Bootstrap) & jQuery",
    ],
    href: "projects/multichoice-landing-login-pages",
    category: "Design",
  },
  {
    client: "Freelance",
    title: "Infinite Grace. A full turnkey solution.",
    image: "/projects/infinite-grace-ybk.png",
    description: [
      "Strategy & planning",
      "Logo design",
      "Digital design",
      "E-mail marketing (MailChimp)",
      "WordPress & hosting",
    ],
    href: "projects/infinite-grace",
    category: "WordPress",
  },

  {
    client: "MultiChoice",
    title: "Creative design for iConnect Africa",
    image: "/projects/multichoice-iconnect.png",
    description: [
      "Creative design",
      "Photoshop manipulation work",
      "UI design",
      "Logo design",
    ],
    href: "projects/multichoice-iconnect",
    category: "Design",
  },
  {
    client: "MultiChoice",
    title: "Department style guide",
    image: "/projects/multichoice-styleguide.png",
    description: [
      "Creative concept",
      "UI design",
      "Copywriting",
      "HTML5 & CSS (Bootstrap)",
    ],
    href: "projects/multichoice-styleguide",
    category: "Design",
  },
  {
    client: "MultiChoice",
    title: "Win a DStv decoder. Web and poster campaign",
    image: "/projects/multichoice-qr-code.png",
    description: [
      "Concept",
      "3D graphic image",
      "Mobile design",
      "Poster design",
    ],
    href: "projects/multichoice-qr-code",
    category: "Design",
  },
  {
    client: "Freelance",
    title: "Definitia Africa. Website design & WordPress",
    image: "/projects/definitia-africa.png",
    description: [
      "Website design",
      "Photoshop work",
      "Logo design",
      "WordPress",
    ],
    href: "projects/definitia-africa",
    category: "WordPress",
  },

  {
    client: "MultiChoice",
    title: "Reducing errors & failures on MultiChoice Africa platforms",
    image: "/projects/multichoice-reducing-errors.png",
    description: [
      "User research",
      "UX strategy & design",
      "Information architecture",
      "Usability testing",
    ],
    href: "",
    category: "UI/UX",
  },
  {
    client: "MultiChoice",
    title: "Headless CMS for ThinkTank",
    image: "/projects/multichoice-thinktank-mobile.png",
    description: [
      "3D design",
      "UI design",
      "HTML & CSS",
      "Print & logo design",
      "WordPress custom theme",
    ],
    href: "projects/multichoice-thinktank",
    category: "WordPress",
  },
  {
    client: "MultiChoice",
    title: "Creative design for 'Commoncents - it just makes sense'",
    image: "/projects/multichoice-commoncents.png",
    description: [
      "Creative design",
      "3D design in Autodesk Maya",
      "Photoshop manipulation",
      "Logo design",
    ],

    href: "projects/multichoice-commoncents",
    category: "Design",
  },
  {
    client: "Freelance",
    title: "My showreel & 3D renders",
    image: "/projects/punctu8-showreel.png",
    description: ["3D design & animation", "Motion graphics"],
    href: "projects/my-showreel",
    category: "Design",
  },
  {
    client: "Freelance",
    title: "Valverde Country Hotel",
    image: "/projects/valverde.png",
    description: [
      "Website & logo design",
      "Photoshop work",
      "WordPress theming",
      "E-mail marketing (MailChimp)",
    ],
    href: "projects/valverde-country-hotel",
    category: "WordPress",
  },

  // {
  //   client: "Agency work",
  //   title: "Samsung Mobile",
  //   image: "/projects/samsung.png",
  //   description: [
  //     "Original design",
  //     "3D design & animation",
  //     "E-mail marketing design",
  //   ],
  //   href: "projects/",
  //   category: "Design",
  // },
  // {
  //   client: "MultiChoice",
  //   title: "SMA Dealer",
  //   image: "/projects/multichoice-sma-dealer.png",
  //   description: [
  //     "UI design",
  //     "Mobile application design",
  //     "Icon set",
  //     "WAP for feature phones",
  //   ],
  //   href: "projects/",
  //   category: "UI/UX",
  // },
  // {
  //   client: "Freelance",
  //   title: "Stratcom",
  //   image: "/projects/stratcom.png",
  //   description: [
  //     "3D design elements",
  //     "HTML5, CSS & jQuery",
  //     "Collaboration with developer",
  //   ],
  //   href: "projects/",
  //   category: "Design",
  // },
  // {
  //   client: "Freelance",
  //   title: "Writing on the Wall",
  //   image: "/projects/writing-wall.png",
  //   description: ["3D visualisations", "WordPress website"],
  //   href: "projects/",
  //   category: "WordPress",
  // },
];
